apiVersion: v1
kind: Service
metadata:
  name: vespa-c
  labels:
    app: vespa-c
spec:
  selector:
    app: vespa-c
  type: NodePort
  ports:
  - name: metricsproxy
    port: 19092
    targetPort: 19092
    protocol: TCP
  - name: configproxy
    port: 19090
    targetPort: 19090
    protocol: TCP
  - name: config
    port: 19071
    targetPort: 19071
    protocol: TCP
